### ISSUE TITLE
Setting r_cubeMapping (macOS Sierra 10.12.4) Crashlog

### ISSUE THREAD

**Issue by refantine** [GrangerHub/tremulous#29]
[crashlog.txt](https://github.com/GrangerHub/tremulous/files/1079471/crashlog.txt)

**Comment by wtfbbqhax** [comment]
@refantine This might be fixed with the latest commit.

**Comment by refantine** [comment]
@wtfbbqhax Occurs when I do /r_cubeMapping 1 and then /vid_restart
