### ISSUE TITLE
Unabled to launch the "release" client

### ISSUE THREAD

**Issue by ObaniGemini** [GrangerHub/tremulous#3]
Debian 8 (Jessie)
Downloaded _release-linux-x86_64.zip_

Launching "granger" I get
> lua script not provided

Launching "tremded" I get
> ./tremded: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9` not found (required by
> ./tremded)
> ./tremded: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21` not found (required by
> ./tremded)

How am I supposed to launch the program ?
Have I some missing libraries ?
(P.S : I tried launching the program from either ~ or ~/(PATH)/GH-releasedir/ )
(P.P.S : I checked the permissions were all right too)

**Comment by ObaniGemini** [comment]
ping

**Comment by cengique** [comment]
@ObaniGemini looks like you have the wrong `libstdc` version :(

**Comment by ObaniGemini** [comment]
For tremded, surely. But I don't get client's error...

**Comment by wtfbbqhax** [comment]
@ObaniGemini I can't fix Debian for being old, talk to me sometime and maybe convince me that I should statically link all of the libc and libc++ and maybe we can make it work at the cost of 10mb for a binary.

**Comment by ObaniGemini** [comment]
@wtfbbqhax :
1 : You may want a maximum of users to use your program
2 : There's no proof here that I'm missing a library or that I have outdated ones. I only want the client to work, and the error message is kinda vague.

**Comment by cengique** [comment]
@ObaniGemini in your case it's best to compile the binary, but I do agree with your point: if we're to offer binaries, maybe they should be static-linked so that people don't get frustrated trying them. What do you think @wtfbbqhax ?
