### ISSUE TITLE
Client crashes on server connect or map change with a z_malloc error on specific maps

### ISSUE THREAD

**Issue by cengique** [GrangerHub/tremulous#31]
Client crashes with error:
```
Z_Malloc: failed on allocation of 16386344 bytes from the main zone
```

Happens on mission_edge and atcs_2015.
[crashlog.txt](https://github.com/GrangerHub/tremulous/files/1117519/crashlog.txt)

Moving all `base/map-*.pk3`s out of the way, or nuking the whole `test7341` folder fixes the problem.

Here're the contents of my pk3s from base, gpp, and test7341 (-old because I had to move it out):
[paks.txt](https://github.com/GrangerHub/tremulous/files/1117522/paks.txt)

**Comment by cengique** [comment]
Issue can be solved by running tremulous like this:
```tremulous +set com_zoneMegs "256"```

There are also variables for `com_hunkMegs` and `com_soundMegs` that may be relevant to similar errors.

**Comment by wtfbbqhax** [comment]
Looking at the code, there "should" be some logging dumped into `qconsole.log` when Z_Malloc fails.

Can you see if you have this log file?

**Comment by cengique** [comment]
No, can't find it. It's not under the home directory.

I think we should keep this issue open until you can set a new default for `com_zoneMegs`. It's retarded to have it at 24 Megs in this age.

**Comment by wtfbbqhax** [comment]
The default in alpha0.8 is 48mb

**Comment by wtfbbqhax** [comment]
@cengique can I close this issue?

**Comment by cengique** [comment]
@wtfbbqhax yes, I confirmed that with the new default 48mb, both of the listed maps above work locally.
