### ISSUE TITLE
shadows pass through at least some surfaces it shouldn't with cg_shadows = "4"

### ISSUE THREAD

**Issue by dGr8LookinSparky** [GrangerHub/tremulous#37]
https://imagebin.ca/v/3TVS7Th9mUHa

shadows passing through a floor on the map archao-1 with cg_shadows = "4" with cl_renderer = "opengl2" on the v1.3.0-alpha.0.9 client.

map download: http://dl.grangerhub.com/base/map-archao-1.pk3

**Comment by wtfbbqhax** [comment]
You should open renderer related bugs over at the ioquake3 project

**Comment by wtfbbqhax** [comment]
Closing this issue, I'm not planning on rewriting any parts of the renderer.
