### ISSUE TITLE
Client crashes if you press tab while the console is open

### ISSUE THREAD

**Issue by dGr8LookinSparky** [GrangerHub/tremulous#39]
I think this issue is related to tab completion.

I get the following back trace from the core dump:

`#0  0x000000000044ba18 in Field_CompleteCommand(char*, bool, bool) ()`
`#1  0x000000000041e0b4 in Console_Key(int) ()`
`#2  0x000000000044af52 in Com_EventLoop() ()`
`#3  0x000000000044b0fe in Com_Frame() ()`
`#4  0x000000000040bec2 in main ()`

**Comment by wtfbbqhax** [comment]
Do you have the full backtrace?

**Comment by wtfbbqhax** [comment]
This is fixed in v1.3.0-alpha.0.10
