### ISSUE TITLE
Bad textures on Linux

### ISSUE THREAD

**Issue by AsciiWolf** [GrangerHub/tremulous#62]
I am having bad textures in the Linux build of Tremulous. It happens only when using the vanila GrangerHub (gpp) game mode, there are no graphical glitches when playing on any custom server.

![tremulous_bad_textures](https://user-images.githubusercontent.com/2339930/33400487-97f83b1a-d556-11e7-935f-d2f0cc3215d1.png)

**Comment by dGr8LookinSparky** [comment]
Looks like you are running the alpha release client with the range markers on (those range markers are glitched) .  For now you can disable the range markers with `cg_rangeMarkerForBlueprint 0`

**Comment by AsciiWolf** [comment]
Thanks, this fixed the issue!
